/**
 * KrishiDrishti Weather & Farm Intelligence Mock Data
 * Realistic meteorological datasets across Indian agricultural locations.
 * Module 2: Current Weather Dashboard
 */

import { LocationWeatherData, WeatherLocation } from '../types/weather';

export const POPULAR_LOCATIONS: WeatherLocation[] = [
  {
    id: 'indore-mp',
    name: 'Indore',
    district: 'Indore',
    state: 'Madhya Pradesh',
    pinCode: '452001',
    latitude: 22.7196,
    longitude: 75.8577,
    agroZone: 'Central Plateau & Hills (Malwa Region)',
    elevationMeters: 553,
    primaryCrops: ['Soybean', 'Wheat', 'Garlic', 'Gram (Chickpea)'],
  },
  {
    id: 'bhopal-mp',
    name: 'Bhopal',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    pinCode: '462001',
    latitude: 23.2599,
    longitude: 77.4126,
    agroZone: 'Vindhya Plateau Agro-Climatic Zone',
    elevationMeters: 527,
    primaryCrops: ['Wheat', 'Gram', 'Soybean', 'Paddy'],
  },
  {
    id: 'ujjain-mp',
    name: 'Ujjain',
    district: 'Ujjain',
    state: 'Madhya Pradesh',
    pinCode: '456001',
    latitude: 23.1765,
    longitude: 75.7885,
    agroZone: 'Malwa Plateau Agro-Climatic Zone',
    elevationMeters: 494,
    primaryCrops: ['Soybean', 'Wheat', 'Garlic', 'Onion'],
  },
  {
    id: 'ranchi-jharkhand',
    name: 'Ranchi',
    district: 'Ranchi',
    state: 'Jharkhand',
    pinCode: '834001',
    latitude: 23.3441,
    longitude: 85.3096,
    agroZone: 'Eastern Plateau & Hills (Chota Nagpur)',
    elevationMeters: 651,
    primaryCrops: ['Paddy', 'Maize', 'Pulses', 'Vegetables'],
  },
  {
    id: 'raipur-chhattisgarh',
    name: 'Raipur',
    district: 'Raipur',
    state: 'Chhattisgarh',
    pinCode: '492001',
    latitude: 21.2514,
    longitude: 81.6296,
    agroZone: 'Chhattisgarh Plains Zone',
    elevationMeters: 298,
    primaryCrops: ['Paddy', 'Lathyrus', 'Gram', 'Mustard'],
  },
  {
    id: 'cuttack-odisha',
    name: 'Cuttack',
    district: 'Cuttack',
    state: 'Odisha',
    pinCode: '753001',
    latitude: 20.4625,
    longitude: 85.8828,
    agroZone: 'East Coast Plains & Hills (Mahanadi Delta)',
    elevationMeters: 36,
    primaryCrops: ['Paddy', 'Pulses', 'Oilseeds', 'Jute'],
  },
  {
    id: 'varanasi-up',
    name: 'Varanasi',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    pinCode: '221001',
    latitude: 25.3176,
    longitude: 82.9739,
    agroZone: 'Middle Gangetic Plain (Zone IV)',
    elevationMeters: 81,
    primaryCrops: ['Wheat', 'Mustard', 'Paddy', 'Potato'],
  },
  {
    id: 'karnal-haryana',
    name: 'Karnal',
    district: 'Karnal',
    state: 'Haryana',
    pinCode: '132001',
    latitude: 29.6857,
    longitude: 76.9905,
    agroZone: 'Trans-Gangetic Plain (Zone VI)',
    elevationMeters: 250,
    primaryCrops: ['Basmati Rice', 'Wheat', 'Mustard'],
  },
];

export const MOCK_WEATHER_DATA_BY_ID: Record<string, LocationWeatherData> = {
  'indore-mp': {
    location: POPULAR_LOCATIONS[0],
    current: {
      temperatureC: 28,
      feelsLikeC: 30,
      tempHighC: 32,
      tempLowC: 24,
      condition: 'partly_cloudy',
      conditionLabel: 'Partly Cloudy',
      conditionDescription: 'Scattered cumulus clouds with gentle breeze. Comfortable daytime conditions.',
      rainProbabilityPercent: 30,
      precipitationMm: 2.4,
      relativeHumidityPercent: 68,
      windSpeedKmh: 14,
      windDirection: 'NW',
      windGustKmh: 24,
      barometricPressureHpa: 950,
      dewPointC: 21,
      uvIndex: 7,
      uvDescription: 'High',
      cloudCoverPercent: 42,
      visibilityKm: 8.5,
      airQualityAqi: 68,
      airQualityStatus: 'Moderate',
      sunrise: '06:16 AM',
      sunset: '06:21 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Partly cloudy conditions are expected today with a low chance of rain and moderate winds.',
      agronomicHeadline: 'Partly cloudy conditions are expected today with a low chance of rain and moderate winds.',
    },
    soil: {
      soilTemperature10cmC: 25,
      soilMoisturePercent: 28,
      soilMoistureStatus: 'Optimal',
      leafWetnessDurationHours: 1.5,
      evapotranspirationEt0Mm: 4.1,
      solarRadiationWattsM2: 700,
      consecutiveDryDays: 3,
      vpdKpa: 1.15,
    },
    hourly: [
      { time: '06:00', displayTime: '6 AM', temperatureC: 24, rainProbabilityPercent: 15, precipitationMm: 0, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 78, windSpeedKmh: 9, windDirection: 'NW', isDaytime: true },
      { time: '09:00', displayTime: '9 AM', temperatureC: 28, rainProbabilityPercent: 20, precipitationMm: 0, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 68, windSpeedKmh: 11, windDirection: 'NW', isDaytime: true },
      { time: '12:00', displayTime: '12 PM', temperatureC: 31, rainProbabilityPercent: 30, precipitationMm: 0.2, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 58, windSpeedKmh: 15, windDirection: 'NW', isDaytime: true },
      { time: '15:00', displayTime: '3 PM', temperatureC: 32, rainProbabilityPercent: 40, precipitationMm: 0.6, condition: 'cloudy', conditionLabel: 'Cloudy', humidityPercent: 54, windSpeedKmh: 18, windDirection: 'NW', isDaytime: true },
      { time: '18:00', displayTime: '6 PM', temperatureC: 28, rainProbabilityPercent: 65, precipitationMm: 1.8, condition: 'light_rain', conditionLabel: 'Rain Showers', humidityPercent: 74, windSpeedKmh: 16, windDirection: 'WNW', isDaytime: false },
      { time: '21:00', displayTime: '9 PM', temperatureC: 25, rainProbabilityPercent: 35, precipitationMm: 0.4, condition: 'cloudy', conditionLabel: 'Passing Clouds', humidityPercent: 79, windSpeedKmh: 12, windDirection: 'NW', isDaytime: false },
      { time: '00:00', displayTime: '12 AM', temperatureC: 24, rainProbabilityPercent: 15, precipitationMm: 0, condition: 'clear', conditionLabel: 'Clear Night', humidityPercent: 82, windSpeedKmh: 8, windDirection: 'NW', isDaytime: false },
      { time: '03:00', displayTime: '3 AM', temperatureC: 23, rainProbabilityPercent: 10, precipitationMm: 0, condition: 'clear', conditionLabel: 'Clear Night', humidityPercent: 85, windSpeedKmh: 7, windDirection: 'NW', isDaytime: false },
      { time: '06:00', displayTime: '6 AM', temperatureC: 24, rainProbabilityPercent: 10, precipitationMm: 0, condition: 'sunny', conditionLabel: 'Sunny Morning', humidityPercent: 76, windSpeedKmh: 8, windDirection: 'NW', isDaytime: true },
    ],
    weatherWindows: [
      {
        id: 'indore-win-stable',
        type: 'stable',
        title: 'Stable Weather',
        timeSlot: '7 AM – 11 AM',
        badgeIcon: '🟢',
        badgeText: 'Stable Weather',
        badgeVariant: 'green',
        description: 'Calm surface winds (8–11 km/h), comfortable temperature (24°C–28°C), and low humidity under partly cloudy sky.',
        metricsHighlight: 'Wind 8–11 km/h · 24°C–28°C · Rain: 15%',
      },
      {
        id: 'indore-win-heat',
        type: 'heat',
        title: 'High Temperature',
        timeSlot: '1 PM – 4 PM',
        badgeIcon: '🌡',
        badgeText: 'High Temperature',
        badgeVariant: 'red',
        description: 'Peak afternoon solar heating with maximum temperature reaching 32°C and high UV index.',
        metricsHighlight: 'Peak: 32°C · Feels like 34°C · UV: 7',
      },
      {
        id: 'indore-win-wind',
        type: 'wind',
        title: 'Strong Winds',
        timeSlot: '2 PM – 5 PM',
        badgeIcon: '💨',
        badgeText: 'Strong Winds',
        badgeVariant: 'amber',
        description: 'Surface winds picking up with gusts peaking between 20 km/h and 24 km/h from the northwest.',
        metricsHighlight: 'Wind 16 km/h NW · Peak Gusts 24 km/h',
      },
      {
        id: 'indore-win-rain',
        type: 'rain',
        title: 'Rain Expected',
        timeSlot: '4 PM – 8 PM',
        badgeIcon: '🌧',
        badgeText: 'Rain Expected',
        badgeVariant: 'blue',
        description: 'Passing convective clouds bringing increased precipitation probability and scattered rain showers.',
        metricsHighlight: 'Rain Chance: 65% · Rainfall: 2.4 mm',
      },
    ],
    todayStatus: {
      status: 'watch',
      badgeIcon: '🟡',
      badgeText: 'Watch',
      headline: 'Rain and stronger winds expected later today.',
      description: 'Convective cloud bands developing in the afternoon with gusty surface winds and scattered showers possible.',
    },
    meteorologicalAlerts: [
      {
        id: 'alert-wind-indore',
        iconType: 'wind',
        title: 'Strong Wind Expected',
        severity: 'CAUTION',
        timePeriod: 'Today, 2:00 PM – 5:00 PM',
        shortDescription: 'Wind speeds may reach 38 km/h between 2 PM and 5 PM.',
        detailedDescription: 'Surface winds will intensify as daytime convective mixing deepens. Gusts ranging between 30 km/h and 38 km/h are expected from the northwest before decreasing by 6 PM.',
        observedParameters: [
          { label: 'Forecast Peak Gust', value: '38 km/h' },
          { label: 'Wind Direction', value: 'North-West (NW)' },
          { label: 'Average Wind Speed', value: '22–26 km/h' },
        ],
      },
      {
        id: 'alert-rain-indore',
        iconType: 'rain',
        title: 'Heavy Rain Expected',
        severity: 'WARNING',
        timePeriod: 'Tomorrow Evening, 5:00 PM – 10:00 PM',
        shortDescription: 'Heavy rainfall is possible tomorrow evening.',
        detailedDescription: 'Synoptic upper-air cyclonic circulation over east-central India is likely to induce moderate to heavy rainfall showers accompanied by occasional thunder.',
        observedParameters: [
          { label: 'Estimated Precipitation', value: '18–35 mm' },
          { label: 'Rain Probability', value: '85%' },
          { label: 'Cloud Cover', value: 'Overcast (80%)' },
        ],
      },
      {
        id: 'alert-heat-indore',
        iconType: 'heat',
        title: 'High Temperature',
        severity: 'INFO',
        timePeriod: 'Saturday, 1:00 PM – 4:00 PM',
        shortDescription: 'Maximum temperature may reach 38°C.',
        detailedDescription: 'Clear skies and dry winds from Rajasthan will elevate local daytime temperatures to around 38°C with elevated solar UV exposure.',
        observedParameters: [
          { label: 'Forecast Maximum Temp', value: '38°C' },
          { label: 'Feels Like (Heat Index)', value: '40°C' },
          { label: 'UV Index', value: '8 (Very High)' },
        ],
      },
    ],
    daily: [
      { date: '2026-09-27', dayName: 'Today', dayShort: 'Today', tempMaxC: 32, tempMinC: 24, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', rainProbabilityPercent: 20, expectedRainfallMm: 0.4, humidityPercent: 68, windSpeedKmh: 14, windDirection: 'NW', uvIndex: 7, et0Mm: 4.1, cropAdvisory: 'Partly cloudy conditions with comfortable daytime temperatures.', sprayingSuitability: 'optimal', irrigationNeed: 'Light' },
      { date: '2026-09-28', dayName: 'Monday', dayShort: 'Mon', tempMaxC: 30, tempMinC: 23, condition: 'light_rain', conditionLabel: 'Scattered Showers', rainProbabilityPercent: 65, expectedRainfallMm: 4.8, humidityPercent: 74, windSpeedKmh: 16, windDirection: 'NW', uvIndex: 6, et0Mm: 3.8, cropAdvisory: 'Passing rain showers with cloud build-up.', sprayingSuitability: 'moderate', irrigationNeed: 'None' },
      { date: '2026-09-29', dayName: 'Tuesday', dayShort: 'Tue', tempMaxC: 28, tempMinC: 22, condition: 'moderate_rain', conditionLabel: 'Rain Showers', rainProbabilityPercent: 85, expectedRainfallMm: 18.5, humidityPercent: 84, windSpeedKmh: 18, windDirection: 'WNW', uvIndex: 5, et0Mm: 3.2, cropAdvisory: 'Elevated rainfall accumulation and cloudy skies.', sprayingSuitability: 'unfavorable', irrigationNeed: 'None' },
      { date: '2026-09-30', dayName: 'Wednesday', dayShort: 'Wed', tempMaxC: 29, tempMinC: 23, condition: 'cloudy', conditionLabel: 'Overcast', rainProbabilityPercent: 40, expectedRainfallMm: 2.1, humidityPercent: 72, windSpeedKmh: 14, windDirection: 'W', uvIndex: 6, et0Mm: 3.6, cropAdvisory: 'Overcast skies with lingering light moisture.', sprayingSuitability: 'moderate', irrigationNeed: 'None' },
      { date: '2026-10-01', dayName: 'Thursday', dayShort: 'Thu', tempMaxC: 31, tempMinC: 23, condition: 'sunny', conditionLabel: 'Clear Sky', rainProbabilityPercent: 10, expectedRainfallMm: 0.0, humidityPercent: 58, windSpeedKmh: 11, windDirection: 'NW', uvIndex: 7, et0Mm: 4.3, cropAdvisory: 'Clearing skies with warm sunshine.', sprayingSuitability: 'optimal', irrigationNeed: 'Light' },
      { date: '2026-10-02', dayName: 'Friday', dayShort: 'Fri', tempMaxC: 32, tempMinC: 22, condition: 'sunny', conditionLabel: 'Sunny', rainProbabilityPercent: 5, expectedRainfallMm: 0.0, humidityPercent: 52, windSpeedKmh: 10, windDirection: 'NW', uvIndex: 8, et0Mm: 4.6, cropAdvisory: 'Sunny weather and low relative humidity.', sprayingSuitability: 'optimal', irrigationNeed: 'Light' },
      { date: '2026-10-03', dayName: 'Saturday', dayShort: 'Sat', tempMaxC: 33, tempMinC: 24, condition: 'sunny', conditionLabel: 'Warm & Sunny', rainProbabilityPercent: 15, expectedRainfallMm: 0.0, humidityPercent: 50, windSpeedKmh: 12, windDirection: 'NW', uvIndex: 8, et0Mm: 4.8, cropAdvisory: 'Peak daytime temperature of the week with dry air.', sprayingSuitability: 'optimal', irrigationNeed: 'Moderate' },
    ],
    windows: [
      {
        id: 'indore-win-spray',
        operationName: 'Chemical & Foliar Spraying Window',
        suitability: 'optimal',
        statusLabel: 'Favorable Window Open',
        recommendedTimeSlot: '06:30 AM – 11:00 AM',
        reasons: ['Wind speed < 15 km/h', 'Temperature < 30°C', 'Rain chance under 30%'],
        keyParameters: [
          { label: 'Wind Speed', value: '14 km/h NW', isFavorable: true },
          { label: 'Temperature', value: '28°C', isFavorable: true },
          { label: 'Rain Risk', value: '30%', isFavorable: true },
        ],
        advice: 'Morning hours suitable for foliar nutrient and organic sprays.',
      },
      {
        id: 'indore-win-field',
        operationName: 'Field Machinery Workability',
        suitability: 'optimal',
        statusLabel: 'Good Field Trafficability',
        recommendedTimeSlot: 'Full Day (07:00 AM – 06:00 PM)',
        reasons: ['Firm soil crust with high bearing strength', 'No excessive standing water'],
        keyParameters: [
          { label: 'Soil Bearing', value: 'Firm', isFavorable: true },
          { label: 'Rainfall', value: '2.4 mm', isFavorable: true },
        ],
        advice: 'Field plowing, harrowing, and intercultural operations can proceed smoothly.',
      },
    ],
    alerts: [
      {
        id: 'alert-indore-weather',
        severity: 'info',
        source: 'IMD Agromet Advisory Malwa Division',
        headline: 'Seasonal Weather Note: Mild Day-Night Temperature Fluctuation',
        issuedAt: '27 Sep 2026, 06:00 AM',
        validUntil: '29 Sep 2026',
        affectedCrops: ['Soybean', 'Wheat Sowing Beds'],
        description: 'Atmospheric pressure stabilized at 950 hPa with moderate northwesterly winds. Partly cloudy sky expected through late afternoon.',
        actionableMeasures: [
          'Store harvested produce in sheltered storage.',
          'Prepare irrigation channels for upcoming rabi pre-sowing.',
        ],
      },
    ],
  },
  'bhopal-mp': {
    location: POPULAR_LOCATIONS[1],
    current: {
      temperatureC: 27,
      feelsLikeC: 29,
      tempHighC: 31,
      tempLowC: 23,
      condition: 'partly_cloudy',
      conditionLabel: 'Partly Cloudy',
      conditionDescription: 'Passing cumulus clouds with gentle westerly winds.',
      rainProbabilityPercent: 25,
      precipitationMm: 1.0,
      relativeHumidityPercent: 65,
      windSpeedKmh: 12,
      windDirection: 'W',
      windGustKmh: 20,
      barometricPressureHpa: 955,
      dewPointC: 20,
      uvIndex: 7,
      uvDescription: 'High',
      cloudCoverPercent: 38,
      visibilityKm: 8.0,
      airQualityAqi: 72,
      airQualityStatus: 'Moderate',
      sunrise: '06:14 AM',
      sunset: '06:19 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Partly cloudy sky with light breeze and low rain likelihood across Bhopal district.',
      agronomicHeadline: 'Partly cloudy sky with light breeze and low rain likelihood across Bhopal district.',
    },
    soil: {
      soilTemperature10cmC: 24,
      soilMoisturePercent: 30,
      soilMoistureStatus: 'Optimal',
      leafWetnessDurationHours: 1.0,
      evapotranspirationEt0Mm: 4.0,
      solarRadiationWattsM2: 690,
      consecutiveDryDays: 2,
      vpdKpa: 1.10,
    },
    hourly: [
      { time: '06:00', displayTime: '6 AM', temperatureC: 23, rainProbabilityPercent: 15, precipitationMm: 0, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 76, windSpeedKmh: 9, windDirection: 'W', isDaytime: true },
      { time: '12:00', displayTime: '12 PM', temperatureC: 30, rainProbabilityPercent: 25, precipitationMm: 0.5, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 58, windSpeedKmh: 13, windDirection: 'W', isDaytime: true },
      { time: '18:00', displayTime: '6 PM', temperatureC: 27, rainProbabilityPercent: 15, precipitationMm: 0, condition: 'clear', conditionLabel: 'Clear', humidityPercent: 65, windSpeedKmh: 10, windDirection: 'W', isDaytime: false },
    ],
    daily: [
      { date: '2026-09-27', dayName: 'Sunday', dayShort: 'Sun', tempMaxC: 31, tempMinC: 23, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', rainProbabilityPercent: 25, expectedRainfallMm: 1.0, humidityPercent: 65, windSpeedKmh: 12, windDirection: 'W', uvIndex: 7, et0Mm: 4.0, cropAdvisory: 'Pleasant weather with scattered sunshine.', sprayingSuitability: 'optimal', irrigationNeed: 'Light' },
    ],
    windows: [],
    alerts: [],
  },
  'ujjain-mp': {
    location: POPULAR_LOCATIONS[2],
    current: {
      temperatureC: 29,
      feelsLikeC: 31,
      tempHighC: 33,
      tempLowC: 24,
      condition: 'sunny',
      conditionLabel: 'Mostly Sunny',
      conditionDescription: 'Warm sunshine with dry Malwa breeze.',
      rainProbabilityPercent: 15,
      precipitationMm: 0.0,
      relativeHumidityPercent: 62,
      windSpeedKmh: 13,
      windDirection: 'NW',
      windGustKmh: 22,
      barometricPressureHpa: 952,
      dewPointC: 20,
      uvIndex: 8,
      uvDescription: 'Very High',
      cloudCoverPercent: 25,
      visibilityKm: 9.0,
      airQualityAqi: 64,
      airQualityStatus: 'Moderate',
      sunrise: '06:17 AM',
      sunset: '06:22 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Predominantly sunny conditions with warm afternoon temperatures and light winds.',
      agronomicHeadline: 'Predominantly sunny conditions with warm afternoon temperatures and light winds.',
    },
    soil: {
      soilTemperature10cmC: 26,
      soilMoisturePercent: 26,
      soilMoistureStatus: 'Optimal',
      leafWetnessDurationHours: 0.5,
      evapotranspirationEt0Mm: 4.4,
      solarRadiationWattsM2: 730,
      consecutiveDryDays: 4,
      vpdKpa: 1.25,
    },
    hourly: [
      { time: '06:00', displayTime: '6 AM', temperatureC: 24, rainProbabilityPercent: 10, precipitationMm: 0, condition: 'clear', conditionLabel: 'Clear', humidityPercent: 74, windSpeedKmh: 8, windDirection: 'NW', isDaytime: true },
      { time: '12:00', displayTime: '12 PM', temperatureC: 32, rainProbabilityPercent: 15, precipitationMm: 0, condition: 'sunny', conditionLabel: 'Sunny', humidityPercent: 52, windSpeedKmh: 14, windDirection: 'NW', isDaytime: true },
    ],
    daily: [
      { date: '2026-09-27', dayName: 'Sunday', dayShort: 'Sun', tempMaxC: 33, tempMinC: 24, condition: 'sunny', conditionLabel: 'Sunny', rainProbabilityPercent: 15, expectedRainfallMm: 0.0, humidityPercent: 62, windSpeedKmh: 13, windDirection: 'NW', uvIndex: 8, et0Mm: 4.4, cropAdvisory: 'Dry conditions favorable for field operations.', sprayingSuitability: 'optimal', irrigationNeed: 'Moderate' },
    ],
    todayStatus: {
      status: 'stable',
      badgeIcon: '🟢',
      badgeText: 'Stable',
      headline: 'No major weather conditions expected.',
      description: 'Pleasant and stable surface conditions prevailing across the district with gentle winds and no active weather warnings.',
    },
    meteorologicalAlerts: [],
    windows: [],
    alerts: [],
  },
  'ranchi-jharkhand': {
    location: POPULAR_LOCATIONS[3],
    current: {
      temperatureC: 26,
      feelsLikeC: 27,
      tempHighC: 28,
      tempLowC: 21,
      condition: 'cloudy',
      conditionLabel: 'Overcast',
      conditionDescription: 'Humid plateau air with dense cloud cover.',
      rainProbabilityPercent: 45,
      precipitationMm: 5.2,
      relativeHumidityPercent: 82,
      windSpeedKmh: 11,
      windDirection: 'SE',
      windGustKmh: 18,
      barometricPressureHpa: 938,
      dewPointC: 22,
      uvIndex: 5,
      uvDescription: 'Moderate',
      cloudCoverPercent: 75,
      visibilityKm: 7.0,
      airQualityAqi: 48,
      airQualityStatus: 'Good',
      sunrise: '05:39 AM',
      sunset: '05:44 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Overcast skies prevailing with intermittent light showers and elevated humidity.',
      agronomicHeadline: 'Overcast skies prevailing with intermittent light showers and elevated humidity.',
    },
    soil: {
      soilTemperature10cmC: 23,
      soilMoisturePercent: 36,
      soilMoistureStatus: 'High',
      leafWetnessDurationHours: 4.0,
      evapotranspirationEt0Mm: 3.2,
      solarRadiationWattsM2: 520,
      consecutiveDryDays: 0,
      vpdKpa: 0.65,
    },
    hourly: [
      { time: '06:00', displayTime: '6 AM', temperatureC: 21, rainProbabilityPercent: 40, precipitationMm: 1.0, condition: 'cloudy', conditionLabel: 'Cloudy', humidityPercent: 90, windSpeedKmh: 8, windDirection: 'SE', isDaytime: true },
      { time: '12:00', displayTime: '12 PM', temperatureC: 27, rainProbabilityPercent: 50, precipitationMm: 2.5, condition: 'light_rain', conditionLabel: 'Light Rain', humidityPercent: 78, windSpeedKmh: 12, windDirection: 'SE', isDaytime: true },
    ],
    daily: [
      { date: '2026-09-27', dayName: 'Sunday', dayShort: 'Sun', tempMaxC: 28, tempMinC: 21, condition: 'light_rain', conditionLabel: 'Showers', rainProbabilityPercent: 45, expectedRainfallMm: 5.2, humidityPercent: 82, windSpeedKmh: 11, windDirection: 'SE', uvIndex: 5, et0Mm: 3.2, cropAdvisory: 'Moist conditions with low solar radiation.', sprayingSuitability: 'unfavorable', irrigationNeed: 'None' },
    ],
    windows: [],
    alerts: [],
  },
  'raipur-chhattisgarh': {
    location: POPULAR_LOCATIONS[4],
    current: {
      temperatureC: 29,
      feelsLikeC: 32,
      tempHighC: 32,
      tempLowC: 24,
      condition: 'partly_cloudy',
      conditionLabel: 'Warm & Humid',
      conditionDescription: 'Warm conditions with humid easterly breeze across the plains.',
      rainProbabilityPercent: 35,
      precipitationMm: 1.8,
      relativeHumidityPercent: 74,
      windSpeedKmh: 10,
      windDirection: 'E',
      windGustKmh: 16,
      barometricPressureHpa: 978,
      dewPointC: 23,
      uvIndex: 6,
      uvDescription: 'Moderate',
      cloudCoverPercent: 50,
      visibilityKm: 7.5,
      airQualityAqi: 58,
      airQualityStatus: 'Moderate',
      sunrise: '05:48 AM',
      sunset: '05:53 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Warm and humid conditions with passing clouds and occasional light drizzle.',
      agronomicHeadline: 'Warm and humid conditions with passing clouds and occasional light drizzle.',
    },
    soil: {
      soilTemperature10cmC: 26,
      soilMoisturePercent: 32,
      soilMoistureStatus: 'Optimal',
      leafWetnessDurationHours: 2.0,
      evapotranspirationEt0Mm: 3.9,
      solarRadiationWattsM2: 630,
      consecutiveDryDays: 1,
      vpdKpa: 0.95,
    },
    hourly: [
      { time: '06:00', displayTime: '6 AM', temperatureC: 24, rainProbabilityPercent: 20, precipitationMm: 0, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 84, windSpeedKmh: 7, windDirection: 'E', isDaytime: true },
      { time: '12:00', displayTime: '12 PM', temperatureC: 31, rainProbabilityPercent: 35, precipitationMm: 1.0, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', humidityPercent: 68, windSpeedKmh: 11, windDirection: 'E', isDaytime: true },
    ],
    daily: [
      { date: '2026-09-27', dayName: 'Sunday', dayShort: 'Sun', tempMaxC: 32, tempMinC: 24, condition: 'partly_cloudy', conditionLabel: 'Partly Cloudy', rainProbabilityPercent: 35, expectedRainfallMm: 1.8, humidityPercent: 74, windSpeedKmh: 10, windDirection: 'E', uvIndex: 6, et0Mm: 3.9, cropAdvisory: 'Humid conditions with adequate ground moisture.', sprayingSuitability: 'moderate', irrigationNeed: 'Light' },
    ],
    windows: [],
    alerts: [],
  },
  'cuttack-odisha': {
    location: POPULAR_LOCATIONS[5],
    current: {
      temperatureC: 30,
      feelsLikeC: 34,
      tempHighC: 33,
      tempLowC: 25,
      condition: 'cloudy',
      conditionLabel: 'Humid Coastal Air',
      conditionDescription: 'Moist sea breeze from Bay of Bengal with scattered cloud formations.',
      rainProbabilityPercent: 40,
      precipitationMm: 3.8,
      relativeHumidityPercent: 80,
      windSpeedKmh: 15,
      windDirection: 'SE',
      windGustKmh: 25,
      barometricPressureHpa: 1008,
      dewPointC: 25,
      uvIndex: 6,
      uvDescription: 'Moderate',
      cloudCoverPercent: 60,
      visibilityKm: 7.0,
      airQualityAqi: 50,
      airQualityStatus: 'Good',
      sunrise: '05:32 AM',
      sunset: '05:37 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Humid conditions with coastal breeze and scattered cloud cover. Rain showers possible.',
      agronomicHeadline: 'Humid conditions with coastal breeze and scattered cloud cover. Rain showers possible.',
    },
    soil: {
      soilTemperature10cmC: 27,
      soilMoisturePercent: 35,
      soilMoistureStatus: 'High',
      leafWetnessDurationHours: 3.0,
      evapotranspirationEt0Mm: 3.8,
      solarRadiationWattsM2: 600,
      consecutiveDryDays: 0,
      vpdKpa: 0.85,
    },
    hourly: [
      { time: '06:00', displayTime: '6 AM', temperatureC: 25, rainProbabilityPercent: 30, precipitationMm: 0.5, condition: 'cloudy', conditionLabel: 'Cloudy', humidityPercent: 88, windSpeedKmh: 12, windDirection: 'SE', isDaytime: true },
      { time: '12:00', displayTime: '12 PM', temperatureC: 32, rainProbabilityPercent: 40, precipitationMm: 2.0, condition: 'cloudy', conditionLabel: 'Cloudy', humidityPercent: 75, windSpeedKmh: 17, windDirection: 'SE', isDaytime: true },
    ],
    daily: [
      { date: '2026-09-27', dayName: 'Sunday', dayShort: 'Sun', tempMaxC: 33, tempMinC: 25, condition: 'cloudy', conditionLabel: 'Humid Overcast', rainProbabilityPercent: 40, expectedRainfallMm: 3.8, humidityPercent: 80, windSpeedKmh: 15, windDirection: 'SE', uvIndex: 6, et0Mm: 3.8, cropAdvisory: 'High humidity and warm coastal breeze.', sprayingSuitability: 'moderate', irrigationNeed: 'None' },
    ],
    windows: [],
    alerts: [],
  },
  'varanasi-up': {
    location: POPULAR_LOCATIONS[6],
    current: {
      temperatureC: 29,
      feelsLikeC: 31,
      tempHighC: 32,
      tempLowC: 24,
      condition: 'partly_cloudy',
      conditionLabel: 'Partly Cloudy',
      conditionDescription: 'Scattered cumulus clouds with gentle northeast breeze.',
      rainProbabilityPercent: 20,
      precipitationMm: 0.0,
      relativeHumidityPercent: 68,
      windSpeedKmh: 9,
      windDirection: 'NE',
      windGustKmh: 14,
      barometricPressureHpa: 1012,
      dewPointC: 22,
      uvIndex: 6,
      uvDescription: 'Moderate',
      cloudCoverPercent: 35,
      visibilityKm: 7.5,
      airQualityAqi: 74,
      airQualityStatus: 'Moderate',
      sunrise: '05:46 AM',
      sunset: '05:52 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Partly cloudy skies with calm conditions and minimal precipitation probability.',
      agronomicHeadline: 'Partly cloudy skies with calm conditions and minimal precipitation probability.',
    },
    soil: {
      soilTemperature10cmC: 26,
      soilMoisturePercent: 28,
      soilMoistureStatus: 'Optimal',
      leafWetnessDurationHours: 1.5,
      evapotranspirationEt0Mm: 4.2,
      solarRadiationWattsM2: 680,
      consecutiveDryDays: 4,
      vpdKpa: 1.18,
    },
    hourly: [],
    daily: [],
    windows: [],
    alerts: [],
  },
  'karnal-haryana': {
    location: POPULAR_LOCATIONS[7],
    current: {
      temperatureC: 28,
      feelsLikeC: 29,
      tempHighC: 31,
      tempLowC: 22,
      condition: 'clear',
      conditionLabel: 'Clear Sky',
      conditionDescription: 'Sunny and dry with light northwesterly winds.',
      rainProbabilityPercent: 5,
      precipitationMm: 0.0,
      relativeHumidityPercent: 56,
      windSpeedKmh: 8,
      windDirection: 'NW',
      windGustKmh: 12,
      barometricPressureHpa: 1014,
      dewPointC: 18,
      uvIndex: 7,
      uvDescription: 'High',
      cloudCoverPercent: 10,
      visibilityKm: 9.0,
      airQualityAqi: 82,
      airQualityStatus: 'Moderate',
      sunrise: '06:14 AM',
      sunset: '06:18 PM',
      updatedAt: '27 Sep 2026, 09:30 AM IST',
      weatherSummary: 'Clear and dry weather prevailing with comfortable humidity and gentle breeze.',
      agronomicHeadline: 'Clear and dry weather prevailing with comfortable humidity and gentle breeze.',
    },
    soil: {
      soilTemperature10cmC: 24,
      soilMoisturePercent: 22,
      soilMoistureStatus: 'Optimal',
      leafWetnessDurationHours: 0.5,
      evapotranspirationEt0Mm: 4.8,
      solarRadiationWattsM2: 740,
      consecutiveDryDays: 8,
      vpdKpa: 1.45,
    },
    hourly: [],
    daily: [],
    windows: [],
    alerts: [],
  },
};

/**
 * Helper to fetch mock weather by location ID with fallback to Indore
 */
export function getWeatherDataForLocation(locationId: string): LocationWeatherData {
  const base = MOCK_WEATHER_DATA_BY_ID[locationId] || MOCK_WEATHER_DATA_BY_ID['indore-mp'];
  const defaultHourly = MOCK_WEATHER_DATA_BY_ID['indore-mp'].hourly;
  const defaultDaily = MOCK_WEATHER_DATA_BY_ID['indore-mp'].daily;
  const defaultWeatherWindows = MOCK_WEATHER_DATA_BY_ID['indore-mp'].weatherWindows;
  const defaultAlerts = MOCK_WEATHER_DATA_BY_ID['indore-mp'].meteorologicalAlerts;
  const defaultStatus = MOCK_WEATHER_DATA_BY_ID['indore-mp'].todayStatus;

  return {
    ...base,
    hourly: base.hourly && base.hourly.length > 0 ? base.hourly : defaultHourly,
    daily: base.daily && base.daily.length === 7 ? base.daily : defaultDaily,
    weatherWindows: base.weatherWindows && base.weatherWindows.length > 0 ? base.weatherWindows : defaultWeatherWindows,
    meteorologicalAlerts:
      base.meteorologicalAlerts !== undefined ? base.meteorologicalAlerts : defaultAlerts,
    todayStatus: base.todayStatus || defaultStatus,
  };
}
